# Zone Management (Zones), Camera Snapshots
from pathlib import Path
from fastapi.responses import FileResponse
from typing import List
from uuid import uuid4
import io
import numpy as np
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from sqlalchemy import and_

from app.core.database import get_db
from app.core.security import get_current_admin
from app.models.admin import Admin
from app.models.camera import Camera
from app.models.zone import Zone
from app.schemas.zone import (
    ZoneCreate,
    ZoneUpdate,
    ZoneResponse,
    ZoneListResponse,
    PolygonCoordinates,
    normalize_zone_type,
    ZONE_TYPE_NORMALIZATION_MAP
)

router = APIRouter()


# 📌 Dynamic search for the main directory containing the data folder
CURRENT_FILE = Path(__file__).resolve()
PROJECT_ROOT = None

for parent in CURRENT_FILE.parents:
    if (parent / "data").exists():
        PROJECT_ROOT = parent
        break

# If not found, set the default path for data
if PROJECT_ROOT:
    REF_FRAMES_DIR = PROJECT_ROOT / "data" / "debug" / "zones" / "reference_frames"
else:
    # Fallback direct path
    REF_FRAMES_DIR = Path("C:/Users/hp/Desktop/restaurant-monitor/data/debug/zones/reference_frames")


@router.get(
    "/cameras/{camera_id}/snapshot",
    summary="Get Camera Snapshot",
    description="Returns the reference image for the specified camera."
)
async def get_camera_snapshot(
    camera_id: str,
    current_admin: Admin = Depends(get_current_admin)
):
    # 1. Search for the reference image for drawing background
    ref_image_jpg = REF_FRAMES_DIR / f"{camera_id}_reference.jpg"
    ref_image_png = REF_FRAMES_DIR / f"{camera_id}_reference.png"

    # Print the path in Terminal to verify the search location
    print(f"📸 Checking for snapshot at: {ref_image_jpg}")

    if ref_image_jpg.exists():
        return FileResponse(path=ref_image_jpg, media_type="image/jpeg")
    elif ref_image_png.exists():
        return FileResponse(path=ref_image_png, media_type="image/png")

    # 2. If no image exists for this specific name
    raise HTTPException(
        status_code=status.HTTP_404_NOT_FOUND,
        detail=f"Image not found for '{camera_id}'. Looked at: {ref_image_jpg}"
    )

@router.get(
    "/cameras/{camera_id}",
    response_model=List[ZoneResponse],
    summary="Retrieve zones for a specific camera",
    description="""
    Retrieves all zones defined for a specific camera ID.
    
    These zones represent regions of interest (ROIs) that can be rendered 
    as map overlays on top of the camera feed in the frontend interface.
    """,
    responses={
        200: {"description": "List of camera zones retrieved successfully"},
        404: {"description": "Camera not found"}
    }
)
async def get_zones_by_camera(
    camera_id: str,
    current_admin: Admin = Depends(get_current_admin),
    db: AsyncSession = Depends(get_db)
):
    """
    Fetch all zones linked to a given camera ID.
    """
    # 1. Verify that the camera exists
    stmt = select(Camera).where(Camera.id == camera_id)
    result = await db.execute(stmt)
    camera = result.scalars().first()
    
    if not camera:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Camera with ID '{camera_id}' was not found"
        )
    
    # 2. Retrieve all zones attached to the camera
    stmt = select(Zone).where(Zone.camera_id == camera_id)
    result = await db.execute(stmt)
    zones = result.scalars().all()
    
    return zones


@router.post(
    "/",
    response_model=ZoneResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Create a new zone",
    description="""
    Creates a new zone of interest (ROI) for a specified camera.
    
    **Required fields:**
    - `camera_id`: Target camera identifier
    - `name`: Display name for the zone
    - `zone_type`: Category classification (automatically normalized: customer_zone→table, staff_zone→work, walkway→walk, kitchen_area→work, entry_exit→walk)
    - `polygon_coordinates`: Geometric coordinate dictionary defining the polygon boundary
    
    **Optional fields:**
    - `parent_zone_id`: ID of the parent zone (if creating a nested sub-zone)
    - `excludes_tables`: Flag indicating whether to exclude table areas
    - `auto_generated`: Flag indicating if the zone was system-generated by AI
    """,
    responses={
        201: {"description": "Zone created successfully"},
        400: {"description": "Invalid request payload"},
        404: {"description": "Specified camera or parent zone not found"}
    }
)
async def create_zone(
    zone_data: ZoneCreate,
    current_admin: Admin = Depends(get_current_admin),
    db: AsyncSession = Depends(get_db)
):
    """
    Create a new region of interest for camera tracking.
    """
    # 1. Verify that the camera exists
    stmt = select(Camera).where(Camera.id == zone_data.camera_id)
    result = await db.execute(stmt)
    camera = result.scalars().first()
    
    if not camera:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Camera with ID '{zone_data.camera_id}' was not found"
        )
    
    # 2. Verify parent_zone_id if provided
    if zone_data.parent_zone_id:
        stmt = select(Zone).where(Zone.id == zone_data.parent_zone_id)
        result = await db.execute(stmt)
        parent_zone = result.scalars().first()
        
        if not parent_zone:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Parent zone with ID '{zone_data.parent_zone_id}' was not found"
            )
    
    # 3. Construct and save the new zone instance
    # Note: zone_type is automatically normalized in Schema for AI Pipeline compatibility
    zone_id = str(uuid4())
    new_zone = Zone(
        id=zone_id,
        camera_id=zone_data.camera_id,
        parent_zone_id=zone_data.parent_zone_id,
        name=zone_data.name,
        zone_type=zone_data.zone_type,  # Normalized value (table/work/walk)
        original_zone_type=zone_data.original_zone_type,
        polygon_coordinates=zone_data.polygon_coordinates.to_dict(),
        auto_generated=zone_data.auto_generated,
        excludes_tables=zone_data.excludes_tables
    )
    
    db.add(new_zone)
    await db.commit()
    await db.refresh(new_zone)
    
    return new_zone


@router.put(
    "/{zone_id}",
    response_model=ZoneResponse,
    summary="Update an existing zone",
    description="""
    Updates attributes of an existing zone (e.g., name, type, coordinates).
    
    All body attributes are optional to support partial updates.
    Only explicitly provided parameters will be modified in the database.
    """,
    responses={
        200: {"description": "Zone updated successfully"},
        400: {"description": "Invalid payload format"},
        404: {"description": "Target zone or referenced parent zone not found"}
    }
)
async def update_zone(
    zone_id: str,
    zone_data: ZoneUpdate,
    current_admin: Admin = Depends(get_current_admin),
    db: AsyncSession = Depends(get_db)
):
    """
    Update details of an existing zone.
    """
    # 1. Verify that the zone exists
    stmt = select(Zone).where(Zone.id == zone_id)
    result = await db.execute(stmt)
    zone = result.scalars().first()
    
    if not zone:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Zone with ID '{zone_id}' was not found"
        )
    
    # 2. Extract set attributes for partial update
    # Note: zone_type is automatically normalized in Schema for AI Pipeline compatibility
    update_data = zone_data.model_dump(exclude_unset=True)
    
    # Properly convert Pydantic coordinate object to dictionary
    if zone_data.polygon_coordinates is not None:
        update_data['polygon_coordinates'] = zone_data.polygon_coordinates.to_dict()
    
    # 3. Verify parent_zone_id if updated
    if zone_data.parent_zone_id is not None:
        stmt = select(Zone).where(Zone.id == zone_data.parent_zone_id)
        result = await db.execute(stmt)
        parent_zone = result.scalars().first()
        
        if not parent_zone:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Parent zone with ID '{zone_data.parent_zone_id}' was not found"
            )
            
    # 4. Apply changes to database model instance
    for field, value in update_data.items():
        setattr(zone, field, value)
    
    await db.commit()
    await db.refresh(zone)
    
    return zone


@router.delete(
    "/{zone_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Delete a zone",
    description="""
    Deletes a specific zone by its unique identifier.
    
    **Warning:** Removing a parent zone will cascade and automatically delete 
    all attached sub-zones due to foreign key `CASCADE` rules.
    """,
    responses={
        204: {"description": "Zone deleted successfully"},
        404: {"description": "Zone not found"}
    }
)
async def delete_zone(
    zone_id: str,
    current_admin: Admin = Depends(get_current_admin),
    db: AsyncSession = Depends(get_db)
):
    """
    Delete a target zone by ID.
    """
    # 1. Check if the target zone exists
    stmt = select(Zone).where(Zone.id == zone_id)
    result = await db.execute(stmt)
    zone = result.scalars().first()
    
    if not zone:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Zone with ID '{zone_id}' was not found"
        )
    
    # 2. Delete zone record
    await db.delete(zone)
    await db.commit()
    
    return None